/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (100000) [Id]
      ,[DocGUID]
      ,[RSId]
      ,[IsActiveDoc]
      ,[CampusId]
      ,[GradeId]
      ,[PersonDataId]
      ,[AccountTemplateId]
      ,[DocDate]
      ,[BoxNumber]
      ,[ScannedBy]
      ,[OriginalDocumentName]
      ,[BatchDocInjId]
      ,[AccountIdMetaData]
      ,[DocIdMetaData]
      ,[ScanningTypeIdMetaData]
      ,[PDFPageCount]
      ,[DescriptionSCM]
      ,[ParentFolderHrefSCM]
      ,[DownloadDocumentHrefSCM]
      ,[DocumentHrefSCM]
      ,[CreatedBy]
      ,[UpdatedBy]
      ,[CreateDt]
      ,[LastUpdatedDt]
      ,[DocumentSize]
      ,[SplitProcessBy]
      ,[IsIndexApply]
      ,[BoxLevelBatchDocInjId]
      ,[DocIndexFlag]
      ,[CustomDocumentName]
      ,[OriginalDocumentName_OldDMS]
      ,[FileTypeId]
      ,[ReindexFlag]
      ,[SalesForceTktId]
      ,[TicketDescription]
      ,[IsDeleted]
      ,[NeedToOCR]
  FROM [yfSBD].[dbo].[tDocDetails]
  WHERE BoxNumber LIKE '%1116%'
